branch-defaults:
  deploy:
    environment: thesis
global:
  application_name: talk
  default_ec2_keyname: air
  default_platform: 64bit Amazon Linux 2016.03 v2.1.3 running Docker 1.11.1
  default_region: ap-southeast-1
  profile: null
  sc: git
